services:
  - type: web
    name: spendwise-app
    env: node
    plan: starter   # or 'free' if you’re on Render free tier
    buildCommand: npm install --include=dev && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
